print("Exploring Huron-Wendat Heritage")
print("Key aspects of Huron-Wendat Culture:")
print("-Traditional Practices")
print("- Art and Craftmanship")
print("- Langauge and Story telling")
print("Community Traditions")
print("Date: Wednesday, November 15, 2023")
print("Duration: 60 Minutes")